### ISSUE TITLE
Organization of this repo

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/debug-tools#1]
How should we organize this repo? Do we want to keep the debug tools as examples or should each tool be added as a separate crate? Keeping the tools as separate crates would have the advantage that the dependencies can be set per crate, but would also make it harder to keep all tools up to date.

Should this repo have CI? Or do want to lower the maintenance effort by only updating tools if we need them?

**Comment by jamwaffles** [comment]
> Do we want to keep the debug tools as examples or should each tool be added as a separate crate?

Would it be an idea to have a "scratchpad" crate so creating e.g. a primitives debugging demo is nice and quick, then anything that needs more dependencies or other stuff could use a whole crate?

> Should this repo have CI? Or do want to lower the maintenance effort by only updating tools if we need them?

I'd be happy to take a PR adding CI, but I don't think much infrastructure is necessary.

**Comment by rfuest** [comment]
> Would it be an idea to have a "scratchpad" crate so creating e.g. a primitives debugging demo is nice and quick, then anything that needs more dependencies or other stuff could use a whole crate?

This also was my first idea, but is it much quicker to copy one example than to copy one of the crates and to change the name in the `Cargo.toml`?

I was also considering to add a simple `cargo-generate` template to make it very easy to quickly test some e-g code using the simulator. Currently I just take a random example and modify it if I want to test some code, which is kind of annoying. Not all of these quick tests will be added to this repo, but I think we could add the templates as branches to this repo. A justfile recipe could make this very convenient: `just new shiny-new-tool`.

> I'd be happy to take a PR adding CI, but I don't think much infrastructure is necessary.

Sorry, I think I didn't make this point very clear. I didn't mean the maintenance of the CI setup, but the crates/examples in this repo. We don't need all tools in the repo constantly, so that it wouldn't be necessary to always keep them working with the latest e-g version. But until we have lots of seldomly used tools in the repo, that could get a maintenance burden, it's probably best to keep them up to date.

**Comment by rfuest** [comment]
Should we just keep things simple and continue to add the tools as examples? I could move the framework crate to the root of this repo and convert the `line` crate into an example.
